---
# If the host has Internet access
- name: Create a directory if it does not exist | zabbix-agent2 | no_internet
  ansible.builtin.file:
    path: "/tmp/os_pkgs"
    state: directory
    mode: '0755'
  tags:
    - install
    - no_internet

- name: Install list of packages | zabbix-agent2
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - smartmontools
    - fping
  tags:
    - packages
    - install

- name: Install list of packages (Debian family) | zabbix-agent2
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo
  when: 
    - ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags:
    - never
    - packages
    - install

# If the host has no internet access
- name: Copy package file to remote (RedHat family) | zabbix-agent2 | no_internet
  ansible.builtin.copy:
    src: "os_pkgs/{{ item }}"
    dest: /tmp/os_pkgs/
  with_items:
    - smartmontools-7.0-2.el7.x86_64.rpm
    - fping-3.10-4.el7.x86_64.rpm
    #- mailx-12.5-19.el7.x86_64.rpm
  when: 
    - ansible_distribution + ansible_distribution_major_version == "CentOS7"
  tags:
    - never
    - no_internet

- name: Download zabbix-agent2-plugin-postgresql package file in local /tmp | sudo | no_internet
  local_action:
    module: ansible.builtin.get_url
    url: "{{ pkg_url.sudo[ ansible_distribution + ansible_distribution_major_version ] }}"
    dest: /tmp
    mode: 644
    timeout: 300
  when: ansible_distribution == "Debian"
  tags:
    - never
    - no_internet

- name: Copy zabbix-agent2-plugin-postgresql package file to remote | sudo | no_internet
  ansible.builtin.copy:
    src: "/tmp/{{ pkg_file.sudo[ ansible_distribution + ansible_distribution_major_version ] }}"
    dest: /tmp
  when: ansible_distribution == "Debian"
  tags:
    - never
    - no_internet

- name: Install package (CentOS7) | zabbix-agent2 | no_internet
  ansible.builtin.yum:
    name: "/tmp/os_pkgs/{{ item }}"
  with_items:
    - smartmontools-7.0-2.el7.x86_64.rpm
    - fping-3.10-4.el7.x86_64.rpm
    #- mailx-12.5-19.el7.x86_64.rpm
  when: 
    - ansible_distribution + ansible_distribution_major_version == "CentOS7"
  tags:
    - never
    - no_internet

- name: Install package (Debian11) | zabbix-agent2 | no_internet
  ansible.builtin.shell: "dpkg -i /tmp/{{ item }}"
  with_items:
    - sudo_1.9.5p2-3+deb11u1_amd64.deb
  when: 
    - ansible_distribution + ansible_distribution_major_version == "Debian11"
  tags:
    - never
    - no_internet
